### ISSUE TITLE
https://github.com/GBoxApp/GBoxSource/issues/1

### ISSUE THREAD

**Issue by moam87moodi** [GBoxApp/GBoxSource#10]
https://github.com/GBoxApp/GBoxSource/issues/1

_Originally posted by @jesulesvf in https://github.com/GBoxApp/GBoxSource/issues/1#issuecomment-674456359_

**Comment by Khalid-1122** [comment]
> #1
> 
> _Originally posted by @jesulesvf in [#1 (comment)](https://github.com/GBoxApp/GBoxSource/issues/1#issuecomment-674456359)_

**Comment by likeremix715** [comment]
> > #- [ ] - - - [ ] #- [x] ******___[![image](https://user-images.githubusercontent.com/77052627/106461070-3d09ea80-64cf-11eb-99fc-23c9e1788440.png)]()___******𝕣✯@@~~~~```
```
```
```

```
```
```
```~~~~
